// Code generated by `golars transpile`. DO NOT EDIT by hand.
package main

import (
	"context"
	"fmt"
	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
	"log"
)

func main() {
	ctx := context.Background()
	_ = ctx
	df1, err := golars.ReadCSV("examples/script/data/salaries.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	lf2 := lazy.FromDataFrame(df1)
	lf2 = lf2.WithColumns(expr.Col("amount").Alias("tier"))
	lf2 = lf2.Filter(expr.Col("amount").Gt(expr.LitInt64(50000)))
	lf2 = lf2.WithColumns(expr.Col("amount").Gt(expr.LitInt64(100000)).Alias("high_earner"))
	lf2 = lf2.GroupBy("high_earner").Agg(expr.Col("amount").Sum().Alias("total_pay"), expr.Col("amount").Mean().Alias("avg_pay"), expr.Col("amount").Count().Alias("n"))
	lf2 = lf2.Sort("total_pay", true)
	{
		out, err := lf2.Head(10).Collect(ctx)
		if err != nil {
			log.Fatal(err)
		}
		defer out.Release()
		fmt.Println(out)
	}
}
