// Code generated by `golars transpile`. DO NOT EDIT by hand.
// Runtime applies lazy.DefaultOptimizer (predicate/slice/projection
// pushdown, CSE, simplify) on each Collect.
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
)

func main() {
	ctx := context.Background()
	df1, err := golars.ReadCSV("examples/script/data/orders.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	lf1 := lazy.FromDataFrame(df1).
		WithColumns(expr.Col("discount").FillNullExpr(expr.LitFloat64(0)).Alias("discount_filled")).
		WithColumns(expr.Col("unit_price").Mul(expr.LitInt64(1).Sub(expr.Col("discount_filled"))).Alias("revenue")).
		Filter(expr.Col("revenue").Gt(expr.LitInt64(0))).
		GroupBy("region").Agg(expr.Col("revenue").Sum().Alias("total_revenue"), expr.Col("revenue").Count().Alias("line_count")).
		Sort("total_revenue", true)
	display(ctx, lf1.Limit(10))
}

// display collects and prints lf, releasing the result on return.
func display(ctx context.Context, lf lazy.LazyFrame) {
	out, err := lf.Collect(ctx)
	if err != nil {
		log.Fatal(err)
	}
	defer out.Release()
	fmt.Println(out)
}
