// Code generated by `golars transpile`. DO NOT EDIT by hand.
package main

import (
	"context"
	"fmt"
	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
	"log"
)

func main() {
	ctx := context.Background()
	_ = ctx
	df1, err := golars.ReadCSV("examples/script/data/orders.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	lf2 := lazy.FromDataFrame(df1)
	lf2 = lf2.WithColumns(expr.Col("discount").FillNullExpr(expr.LitFloat64(0)).Alias("discount_filled"))
	lf2 = lf2.WithColumns(expr.Col("unit_price").Mul(expr.LitInt64(1).Sub(expr.Col("discount_filled"))).Alias("revenue"))
	lf2 = lf2.Filter(expr.Col("revenue").Gt(expr.LitInt64(0)))
	lf2 = lf2.GroupBy("region").Agg(expr.Col("revenue").Sum().Alias("total_revenue"), expr.Col("revenue").Count().Alias("line_count"))
	lf2 = lf2.Sort("total_revenue", true)
	{
		out, err := lf2.Head(10).Collect(ctx)
		if err != nil {
			log.Fatal(err)
		}
		defer out.Release()
		fmt.Println(out)
	}
}
