// Code generated by `golars transpile`. DO NOT EDIT by hand.
package main

import (
	"context"
	"fmt"
	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
	"log"
)

func main() {
	ctx := context.Background()
	_ = ctx
	df1, err := golars.ReadCSV("examples/script/data/people.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	lf2 := lazy.FromDataFrame(df1)
	lf2 = lf2.WithColumns(expr.Col("name").Str().ToUpper().Alias("name_caps"))
	lf2 = lf2.WithColumns(expr.Col("name").Str().Head(2).Alias("first_two"))
	lf2 = lf2.Filter(expr.Col("name").Str().Like("a%"))
	{
		out, err := lf2.Head(10).Collect(ctx)
		if err != nil {
			log.Fatal(err)
		}
		defer out.Release()
		fmt.Println(out)
	}
	// TODO(glr): command "reset" has no direct lazy API; port manually
	df3, err := golars.ReadCSV("examples/script/data/people.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df3.Release()
	lf4 := lazy.FromDataFrame(df3)
	lf4 = lf4.Filter(expr.Col("name").Str().Contains("a"))
	{
		out, err := lf4.Head(10).Collect(ctx)
		if err != nil {
			log.Fatal(err)
		}
		defer out.Release()
		fmt.Println(out)
	}
	// TODO(glr): command "reset" has no direct lazy API; port manually
	df5, err := golars.ReadCSV("examples/script/data/people.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df5.Release()
	lf6 := lazy.FromDataFrame(df5)
	lf6 = lf6.WithColumns(expr.Col("name").Str().ContainsRegex("[aeiou]").Alias("matches_vowel"))
	lf6 = lf6.Filter(expr.Col("matches_vowel"))
	{
		out, err := lf6.Head(10).Collect(ctx)
		if err != nil {
			log.Fatal(err)
		}
		defer out.Release()
		fmt.Println(out)
	}
}
