// Code generated by `golars transpile`. DO NOT EDIT by hand.
// Runtime applies lazy.DefaultOptimizer (predicate/slice/projection
// pushdown, CSE, simplify) on each Collect.
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
)

func main() {
	ctx := context.Background()
	df1, err := golars.ReadCSV("examples/script/data/people.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	lf1 := lazy.FromDataFrame(df1).
		WithColumns(expr.Col("name").Str().ToUpper().Alias("name_caps")).
		WithColumns(expr.Col("name").Str().Head(2).Alias("first_two")).
		Filter(expr.Col("name").Str().Like("a%"))
	display(ctx, lf1.Limit(10))
	df2, err := golars.ReadCSV("examples/script/data/people.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df2.Release()
	lf2 := lazy.FromDataFrame(df2).Filter(expr.Col("name").Str().Contains("a"))
	display(ctx, lf2.Limit(10))
	df3, err := golars.ReadCSV("examples/script/data/people.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df3.Release()
	lf3 := lazy.FromDataFrame(df3).
		WithColumns(expr.Col("name").Str().ContainsRegex("[aeiou]").Alias("matches_vowel")).
		Filter(expr.Col("matches_vowel"))
	display(ctx, lf3.Limit(10))
}

// display collects and prints lf, releasing the result on return.
func display(ctx context.Context, lf lazy.LazyFrame) {
	out, err := lf.Collect(ctx)
	if err != nil {
		log.Fatal(err)
	}
	defer out.Release()
	fmt.Println(out)
}
