package dataframe_test

// frameExpected holds polars 1.39.3 output for the frame parity tests,
// rendered with internal/framerepr. Generated by running the matching
// polars script and pasted verbatim.
var frameExpected = map[string]string{
	"sum": `i8:i64|i32:i32|i64:i64|u16:i64|u32:u32|u64:u64|f32:f32|f64:f64|s:str|b:u32|d:date|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
11|10|7|15|6|11|2.75|nan|null|2|null|null|16200000000us|null|null`,
	"mean": `i8:f64|i32:f64|i64:f64|u16:f64|u32:f64|u64:f64|f32:f32|f64:f64|s:str|b:f64|d:datetime[us]|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
3.6666666666666665|2.5|2.3333333333333335|3.75|2.0|2.75|0.9166666865348816|nan|null|0.6666666666666666|2020-01-02T08:00:00.000000|2020-01-02T04:00:00.000000|5400000000us|null|null`,
	"median": `i8:f64|i32:f64|i64:f64|u16:f64|u32:f64|u64:f64|f32:f32|f64:f64|s:str|b:f64|d:datetime[us]|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
3.0|2.5|3.0|2.5|2.0|2.5|1.5|2.0|null|1.0|2020-01-02T00:00:00.000000|2020-01-02T12:00:00.000000|3600000000us|null|null`,
	"min": `i8:i8|i32:i32|i64:i64|u16:u16|u32:u32|u64:u64|f32:f32|f64:f64|s:str|b:bool|d:date|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
1|1|1|1|1|1|-1.0|1.5|"a"|false|2020-01-01|2020-01-01T00:00:00.000000|1800000000us|null|null`,
	"max": `i8:i8|i32:i32|i64:i64|u16:u16|u32:u32|u64:u64|f32:f32|f64:f64|s:str|b:bool|d:date|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
7|4|3|9|3|5|2.25|2.0|"b"|true|2020-01-04|2020-01-03T00:00:00.000000|10800000000us|null|null`,
	"std": `i8:f64|i32:f64|i64:f64|u16:f64|u32:f64|u64:f64|f32:f32|f64:f64|s:str|b:f64|d:date|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
3.0550504633038935|1.2909944487358056|1.1547005383792515|3.593976442141304|1.0|1.707825127659933|1.7017148733139038|nan|null|0.5773502691896258|null|null|null|null|null`,
	"var": `i8:f64|i32:f64|i64:f64|u16:f64|u32:f64|u64:f64|f32:f32|f64:f64|s:str|b:f64|d:date|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
9.333333333333334|1.6666666666666667|1.3333333333333333|12.916666666666666|1.0|2.9166666666666665|2.8958332538604736|nan|null|0.33333333333333337|null|null|null|null|null`,
	"product": `i8:i64|i32:i64|i64:i64|u16:i64|u32:i64|u64:u64|f32:f32|f64:f64|s:null|b:i64|d:null|dt:null|du:null|n:null|l:null
21|24|9|54|6|30|-3.375|nan|null|0|null|null|null|null|null`,
	"null_count": `i8:u32|i32:u32|i64:u32|u16:u32|u32:u32|u64:u32|f32:u32|f64:u32|s:u32|b:u32|d:u32|dt:u32|du:u32|n:u32|l:u32
1|0|1|0|1|0|1|1|1|1|1|1|1|4|1`,
	"count": `i8:u32|i32:u32|i64:u32|u16:u32|u32:u32|u64:u32|f32:u32|f64:u32|s:u32|b:u32|d:u32|dt:u32|du:u32|n:u32|l:u32
3|4|3|4|3|4|3|3|3|3|3|3|3|0|3`,
	"quantile 0.5 nearest": `i8:f64|i32:f64|i64:f64|u16:f64|u32:f64|u64:f64|f32:f32|f64:f64|s:str|b:bool|d:datetime[us]|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
3.0|3.0|3.0|3.0|2.0|3.0|1.5|2.0|null|null|2020-01-02T00:00:00.000000|2020-01-02T12:00:00.000000|3600000000us|null|null`,
	"quantile 0.25 linear": `i8:f64|i32:f64|i64:f64|u16:f64|u32:f64|u64:f64|f32:f32|f64:f64|s:str|b:bool|d:datetime[us]|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
2.0|1.75|2.0|1.75|1.5|1.75|0.25|1.75|null|null|2020-01-01T12:00:00.000000|2020-01-01T18:00:00.000000|2700000000us|null|null`,
	"quantile 0.75 higher": `i8:f64|i32:f64|i64:f64|u16:f64|u32:f64|u64:f64|f32:f32|f64:f64|s:str|b:bool|d:datetime[us]|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
7.0|4.0|3.0|9.0|3.0|5.0|2.25|nan|null|null|2020-01-04T00:00:00.000000|2020-01-03T00:00:00.000000|10800000000us|null|null`,
	"quantile 0.3 lower": `i8:f64|i32:f64|i64:f64|u16:f64|u32:f64|u64:f64|f32:f32|f64:f64|s:str|b:bool|d:datetime[us]|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
1.0|1.0|1.0|1.0|1.0|1.0|-1.0|1.5|null|null|2020-01-01T00:00:00.000000|2020-01-01T00:00:00.000000|1800000000us|null|null`,
	"quantile 0.4 midpoint": `i8:f64|i32:f64|i64:f64|u16:f64|u32:f64|u64:f64|f32:f32|f64:f64|s:str|b:bool|d:datetime[us]|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
2.0|2.5|2.0|2.5|1.5|2.5|0.25|1.75|null|null|2020-01-01T12:00:00.000000|2020-01-01T18:00:00.000000|2700000000us|null|null`,
	"quantile 0.6 equiprobable": `i8:f64|i32:f64|i64:f64|u16:f64|u32:f64|u64:f64|f32:f32|f64:f64|s:str|b:bool|d:datetime[us]|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
3.0|3.0|3.0|3.0|2.0|3.0|1.5|2.0|null|null|2020-01-02T00:00:00.000000|2020-01-02T12:00:00.000000|3600000000us|null|null`,
	"std ddof0": `i8:f64|i32:f64|i64:f64|u16:f64|u32:f64|u64:f64|f32:f32|f64:f64|s:str|b:f64|d:date|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
2.494438257849294|1.118033988749895|0.9428090415820634|3.112474899497183|0.816496580927726|1.479019945774904|1.389444351196289|nan|null|0.4714045207910317|null|null|null|null|null`,
	"var ddof3": `i8:f64|i32:f64|i64:f64|u16:f64|u32:f64|u64:f64|f32:f32|f64:f64|s:str|b:f64|d:date|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
null|5.0|null|38.75|null|8.75|null|null|null|null|null|null|null|null|null`,
	"empty sum": `i8:i64|i32:i32|i64:i64|u16:i64|u32:u32|u64:u64|f32:f32|f64:f64|s:str|b:u32|d:date|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
0|0|0|0|0|0|0.0|0.0|null|0|null|null|0us|null|null`,
	"empty mean": `i8:f64|i32:f64|i64:f64|u16:f64|u32:f64|u64:f64|f32:f32|f64:f64|s:str|b:f64|d:datetime[us]|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
null|null|null|null|null|null|null|null|null|null|null|null|null|null|null`,
	"empty min": `i8:i8|i32:i32|i64:i64|u16:u16|u32:u32|u64:u64|f32:f32|f64:f64|s:str|b:bool|d:date|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
null|null|null|null|null|null|null|null|null|null|null|null|null|null|null`,
	"empty std": `i8:f64|i32:f64|i64:f64|u16:f64|u32:f64|u64:f64|f32:f32|f64:f64|s:str|b:f64|d:date|dt:datetime[us]|du:duration[us]|n:null|l:list[i64]
null|null|null|null|null|null|null|null|null|null|null|null|null|null|null`,
	"empty product": `i8:i64|i32:i64|i64:i64|u16:i64|u32:i64|u64:u64|f32:f32|f64:f64|s:null|b:i64|d:null|dt:null|du:null|n:null|l:null
1|1|1|1|1|1|1.0|1.0|null|1|null|null|null|null|null`,
	"empty count": `i8:u32|i32:u32|i64:u32|u16:u32|u32:u32|u64:u32|f32:u32|f64:u32|s:u32|b:u32|d:u32|dt:u32|du:u32|n:u32|l:u32
0|0|0|0|0|0|0|0|0|0|0|0|0|0|0`,
	"approx_n_unique": `i8:u32|i32:u32|i64:u32|u16:u32|u32:u32|u64:u32|f32:u32|f64:u32|s:u32|b:u32|d:u32|dt:u32|du:u32|n:u32
4|4|3|4|4|4|4|4|3|3|4|4|4|1`,
	"is_duplicated": `:bool
true
false
true
false
false`,
	"is_unique": `:bool
false
true
false
true
true`,
	"shift 2": `a:i64|b:str|f:f64
null|null|null
null|null|null
1|"x"|1.0
2|"y"|nan
1|"x"|1.0`,
	"shift -1 fill 0": `a:i64|f:f64
2|nan
1|1.0
null|null
1|3.0
0|0.0`,
	"shift 1 fill 2.5": `a:f64
2.5
1.0
2.0
1.0
null`,
	"shift 1 fill q": `b:str
"q"
"x"
"y"
"x"
null`,
	"shift 9 fill 9": `a:i64
9
9
9
9
9`,
	"gather_every 2": `a:i64|b:str|f:f64
1|"x"|1.0
1|"x"|1.0
1|"z"|3.0`,
	"gather_every 2 1": `a:i64|b:str|f:f64
2|"y"|nan
null|null|null`,
	"fill_nan 0.5": `a:i64|b:str|f:f64
1|"x"|1.0
2|"y"|0.5
1|"x"|1.0
null|null|null
1|"z"|3.0`,
	"fill_nan null": `a:i64|b:str|f:f64
1|"x"|1.0
2|"y"|null
1|"x"|1.0
null|null|null
1|"z"|3.0`,
	"drop_nans": `a:i64|b:str|f:f64
1|"x"|1.0
1|"x"|1.0
null|null|null
1|"z"|3.0`,
	"drop_nans a": `a:i64|b:str|f:f64
1|"x"|1.0
2|"y"|nan
1|"x"|1.0
null|null|null
1|"z"|3.0`,
	"fill_null forward": `a:i64|b:str|f:f64
1|"x"|1.0
2|"y"|nan
1|"x"|1.0
1|"x"|1.0
1|"z"|3.0`,
	"fill_null backward": `a:i64|b:str|f:f64
1|"x"|1.0
2|"y"|nan
1|"x"|1.0
1|"z"|3.0
1|"z"|3.0`,
	"fill_null min": `a:i64|b:str|f:f64
1|"x"|1.0
2|"y"|nan
1|"x"|1.0
1|"x"|1.0
1|"z"|3.0`,
	"fill_null max": `a:i64|b:str|f:f64
1|"x"|1.0
2|"y"|nan
1|"x"|1.0
2|"z"|3.0
1|"z"|3.0`,
	"fill_null zero": `a:i64|b:str|f:f64
1|"x"|1.0
2|"y"|nan
1|"x"|1.0
0|""|0.0
1|"z"|3.0`,
	"fill_null mean": `a:i64|f:f32|u:u8
1|1.0|1
2|2.5|1
3|2.5|2
4|4.0|3
3|2.5|1
3|2.5|1
7|2.5|1`,
	"fill_null one": `a:i64|f:f32|u:u8
1|1.0|1
2|1.0|1
1|2.5|2
4|4.0|3
1|1.0|1
1|1.0|1
7|1.0|1`,
	"fill_null forward 1": `a:i64|f:f32|u:u8
1|1.0|1
2|1.0|1
2|2.5|2
4|4.0|3
4|4.0|3
null|null|1
7|null|1`,
	"fill_null backward 1": `a:i64|f:f32|u:u8
1|1.0|1
2|2.5|2
4|2.5|2
4|4.0|3
null|null|1
7|null|1
7|null|1`,
	"with_row_index": `index:u32|a:i64|b:str|f:f64
0|1|"x"|1.0
1|2|"y"|nan
2|1|"x"|1.0
3|null|null|null
4|1|"z"|3.0`,
	"with_row_index rn 10": `rn:u32|a:i64|b:str|f:f64
10|1|"x"|1.0
11|2|"y"|nan
12|1|"x"|1.0
13|null|null|null
14|1|"z"|3.0`,
	"to_dummies": `a_1:u8|a_2:u8|a_null:u8|b_null:u8|b_x:u8|b_y:u8|b_z:u8
1|0|0|0|1|0|0
0|1|0|0|0|1|0
1|0|0|0|1|0|0
0|0|1|1|0|0|0
1|0|0|0|0|0|1`,
	"to_dummies drop_first": `a_2:u8|a_null:u8|b_null:u8|b_y:u8|b_z:u8
0|0|0|0|0
1|0|0|1|0
0|0|0|0|0
0|1|1|0|0
0|0|0|0|1`,
	"to_dummies b sep": `a:i64|b:null:u8|b:x:u8|b:y:u8|b:z:u8|f:f64
1|0|1|0|0|1.0
2|0|0|1|0|nan
1|0|1|0|0|1.0
null|1|0|0|0|null
1|0|0|0|1|3.0`,
	"to_dummies drop_nulls": `a_1:u8|a_2:u8|b_x:u8|b_y:u8|b_z:u8
1|0|1|0|0
0|1|0|1|0
1|0|1|0|0
0|0|0|0|0
1|0|0|0|1`,
	"to_dummies mixed": `a_-1:u8|a_10:u8|a_9:u8|a_null:u8|f_-2.0:u8|f_1.5:u8|f_null:u8|b_false:u8|b_null:u8|b_true:u8
0|1|0|0|0|1|0|0|0|1
0|0|1|0|0|0|1|0|1|0
0|0|0|1|1|0|0|1|0|0
1|0|0|0|0|1|0|0|0|1`,
	"to_struct": `s:struct{a: i64, b: str, f: f64}
{a=1,b="x",f=1.0}
{a=2,b="y",f=nan}
{a=1,b="x",f=1.0}
{a=null,b=null,f=null}
{a=1,b="z",f=3.0}`,
	"insert_column -1": `a:i64|b:str|z:i64|f:f64
1|"x"|9|1.0
2|"y"|8|nan
1|"x"|7|1.0
null|null|6|null
1|"z"|5|3.0`,
	"insert_column 3": `a:i64|b:str|f:f64|z:i64
1|"x"|1.0|9
2|"y"|nan|8
1|"x"|1.0|7
null|null|null|6
1|"z"|3.0|5`,
	"replace_column 1": `a:i64|q:i64|f:f64
1|0|1.0
2|0|nan
1|0|1.0
null|0|null
1|0|3.0`,
	"fold add": `a:f64
2.0
nan
2.0
null
4.0`,
	"map_rows tuple": `column_0:i64|column_1:str
1|"q"
2|"q"
1|"q"
null|"q"
1|"q"`,
	"map_rows scalar": `map:i64
2
4
2
2
2`,
	"unstack v3": `x_0:str|x_1:str|x_2:str|y_0:i64|y_1:i64|y_2:i64
"A"|"D"|"G"|0|3|6
"B"|"E"|"H"|1|4|7
"C"|"F"|"I"|2|5|8`,
	"unstack h3": `x_0:str|x_1:str|x_2:str|y_0:i64|y_1:i64|y_2:i64
"A"|"B"|"C"|0|1|2
"D"|"E"|"F"|3|4|5
"G"|"H"|"I"|6|7|8`,
	"unstack v4": `x_0:str|x_1:str|x_2:str|y_0:i64|y_1:i64|y_2:i64
"A"|"E"|"I"|0|4|8
"B"|"F"|null|1|5|null
"C"|"G"|null|2|6|null
"D"|"H"|null|3|7|null`,
	"unstack h4 fill -1": `x_0:str|x_1:str|x_2:str|x_3:str|y_0:i64|y_1:i64|y_2:i64|y_3:i64
"A"|"B"|"C"|"D"|0|1|2|3
"E"|"F"|"G"|"H"|4|5|6|7
"I"|"-1"|"-1"|"-1"|8|-1|-1|-1`,
	"unstack y 2": `y_0:i64|y_1:i64|y_2:i64|y_3:i64|y_4:i64
0|2|4|6|8
1|3|5|7|null`,
	"update rows": `A:i64|B:i64
1|-66
2|500
3|-99
4|700`,
	"update rows nulls": `A:i64|B:i64
1|-66
2|null
3|-99
4|700`,
	"update rows full": `A:i64|B:i64
1|1
2|2
3|3
4|4`,
	"update on": `A:i64|B:i64
1|-99
2|500
3|600
4|700`,
	"update on inner": `A:i64|B:i64
1|-99
3|600`,
	"update on full": `A:i64|B:i64
1|-99
2|500
3|600
4|700
5|-66`,
	"update on full nulls": `A:i64|B:i64
1|-99
2|500
3|null
4|700
5|-66`,
	"update dup": `A:i64|B:f64
1|400.0
1|7.0
2|500.0
3|1.5
4|700.0`,
	"update dup full": `A:i64|B:f64
1|400.0
1|7.0
2|500.0
3|1.5
4|700.0
9|3.0`,
	"merge_sorted": `k:i64|v:str
null|"n1"
null|"n2"
1|"a"
2|"x"
3|"b"
3|"y"
4|"z"
5|"c"`,
	"merge_sorted str": `k:str
"a"
"b"
"c"
"c"
"d"`,
	"match_to_schema": `b:str|a:i64|z:f64
"x"|1|null
"y"|2|null`,
	"cast map": `a:f64|b:str|c:i64
1.0|"x"|1
2.0|"y"|2
3.0|"z"|null`,
	"cast dtypes": `a:str|b:str|c:f32
"1"|"x"|1.5
"2"|"y"|2.5
"3"|"z"|null`,
	"cast all": `a:f32|b:f32
1.0|3.0
2.0|4.0`,
	"cast nonstrict": `a:i64
1
null`,
}
