package exprparse

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	goparser "go/parser"
	gotoken "go/token"
	"os"
	"sort"
	"strings"
	"testing"
)

var updateGoDocs = flag.Bool("update", false, "rewrite godocs.go from the expr package sources")

// TestGoDocsUpToDate keeps godocs.go in sync with the doc comments
// and parameter names of the expr package. Editors show them in hover
// and signature help, and a release binary has no Go sources to read,
// so the table is checked in. Run
//
//	go test ./script/exprparse -run TestGoDocsUpToDate -update
//
// after changing a documented expr API.
func TestGoDocsUpToDate(t *testing.T) {
	want := renderGoDocs(t, extractGoDocs(t, "../../expr"))
	got, err := os.ReadFile("godocs.go")
	if err != nil && !*updateGoDocs {
		t.Fatal(err)
	}
	if bytes.Equal(got, want) {
		return
	}
	if *updateGoDocs {
		if err := os.WriteFile("godocs.go", want, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	t.Fatal("godocs.go is stale: run go test ./script/exprparse -run TestGoDocsUpToDate -update")
}

func extractGoDocs(t *testing.T, dir string) map[string]goDoc {
	t.Helper()
	fset := gotoken.NewFileSet()
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	var files []*ast.File
	for _, e := range entries {
		name := e.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, err := goparser.ParseFile(fset, dir+"/"+name, nil, goparser.ParseComments)
		if err != nil {
			t.Fatal(err)
		}
		files = append(files, f)
	}
	receivers := map[string]bool{}
	for _, rt := range nsTypes {
		receivers[rt.Name()] = true
	}
	out := map[string]goDoc{}
	for _, f := range files {
		for _, decl := range f.Decls {
			fd, isFunc := decl.(*ast.FuncDecl)
			if !isFunc || !fd.Name.IsExported() {
				continue
			}
			key := fd.Name.Name
			if fd.Recv != nil {
				recv := typeName(fd.Recv.List[0].Type)
				if !receivers[recv] {
					continue
				}
				key = recv + "." + key
			}
			var params []string
			for _, field := range fd.Type.Params.List {
				if len(field.Names) == 0 {
					params = append(params, "_")
				}
				for _, n := range field.Names {
					params = append(params, n.Name)
				}
			}
			text := ""
			if fd.Doc != nil {
				text = strings.TrimSpace(fd.Doc.Text())
			}
			out[key] = goDoc{params: params, doc: text}
		}
	}
	return out
}

func typeName(e ast.Expr) string {
	switch x := e.(type) {
	case *ast.Ident:
		return x.Name
	case *ast.StarExpr:
		return typeName(x.X)
	}
	return ""
}

func renderGoDocs(t *testing.T, docs map[string]goDoc) []byte {
	t.Helper()
	keys := make([]string, 0, len(docs))
	for k := range docs {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b bytes.Buffer
	b.WriteString("// Code generated by TestGoDocsUpToDate from the expr package; DO NOT EDIT.\n\n")
	b.WriteString("package exprparse\n\n")
	b.WriteString("// goDocs holds the doc comment and parameter names of every exported\n")
	b.WriteString("// function and namespace method in the expr package, keyed by\n")
	b.WriteString("// \"Type.Method\" or by function name.\n")
	b.WriteString("var goDocs = map[string]goDoc{\n")
	for _, k := range keys {
		d := docs[k]
		fmt.Fprintf(&b, "%q: {params: %#v, doc: %q},\n", k, d.params, d.doc)
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		t.Fatal(err)
	}
	return src
}
