// Code generated by `golars transpile`. DO NOT EDIT by hand.
// Runtime applies lazy.DefaultOptimizer (predicate/slice/projection
// pushdown, CSE, simplify) on each Collect.
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/dataframe"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
)

func main() {
	ctx := context.Background()
	df1, err := golars.ReadCSV("examples/script/data/rates.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	rates := lazy.FromDataFrame(df1)
	df2, err := golars.ReadCSV("examples/script/data/events.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df2.Release()
	lf1 := lazy.FromDataFrame(df2).
		WithColumns(expr.Col("signup").Str().ToDate("%d/%m/%Y").Alias("signed_up")).
		WithColumns(expr.Col("ts").Dt().Date().Sub(expr.Col("signed_up")).Dt().TotalDays().Alias("tenure_d")).
		WithColumns(expr.Col("ts").Dt().Hour().Alias("hour")).
		WithColumns(expr.Col("ts").Dt().Truncate("30m").Dt().Strftime("%H:%M").Alias("slot")).
		WithColumns(expr.Col("tags").Str().Split(";").List().Len().Alias("ntags")).
		WithColumns(expr.Col("tags").Str().Split(";").List().First().Alias("main_tag")).
		WithColumns(expr.Col("tags").Str().Split(";").List().Contains("api").Alias("has_api")).
		WithColumns(expr.Col("amount").Cut([]float64{20, 100}, expr.CutOptions{Labels: []string{"small", "medium", "large"}}).Alias("size")).
		WithColumns(expr.Col("amount").FloorDiv(expr.LitInt64(50)).Mul(expr.LitInt64(50)).Alias("bucket")).
		WithColumns(expr.When(expr.Col("amount").Mod(expr.LitInt64(2)).Eq(expr.LitInt64(0))).Then(expr.LitString("even")).Otherwise(expr.LitString("odd")).Alias("parity")).
		WithColumns(expr.ConcatStr("/", expr.Col("user").Str().ToUpper(), expr.Col("size")).Alias("label")).
		Drop("tags", "signup")
	display(ctx, lf1.Limit(10))
	lf1 = lf1.
		Filter(expr.Col("user").IsIn("ada", "bo").And(expr.Col("has_api").Not())).
		Select(expr.Col("ts"), expr.Col("user"), expr.Col("amount"), expr.Col("size"), expr.Col("amount").Div(expr.Col("amount").Sum()).Alias("share"))
	display(ctx, lf1.Limit(10))
	lf2 := lazy.FromDataFrame(df2).
		JoinAsof(rates, dataframe.AsofOptions{On: "ts", By: []string{"user"}, Tolerance: "2h"}).
		WithColumns(expr.Col("amount").Mul(expr.Col("rate")).Round(2).Alias("value")).
		Select(expr.Col("ts"), expr.Col("user"), expr.Col("amount"), expr.Col("rate"), expr.Col("value"))
	display(ctx, lf2.Limit(10))
	priced := lf2
	lf2 = lf2.GroupByDynamic("ts", dataframe.DynamicGroupOptions{Every: "1h"}).Agg(expr.Col("amount").Sum().Alias("total"), expr.Col("value").Sum().Alias("value"), expr.Col("amount").Count().Alias("n"))
	display(ctx, lf2.Limit(10))
	lf3 := priced.Select(expr.Col("user"), expr.Col("amount"))
	df3, err := lf3.Collect(ctx)
	if err != nil {
		log.Fatal(err)
	}
	defer df3.Release()
	df4, err := df3.ToDummies(ctx, dataframe.ToDummiesOptions{Columns: []string{"user"}})
	if err != nil {
		log.Fatal(err)
	}
	defer df4.Release()
	lf4 := lazy.FromDataFrame(df4)
	display(ctx, lf4.Limit(10))
}

// display collects and prints lf, releasing the result on return.
func display(ctx context.Context, lf lazy.LazyFrame) {
	out, err := lf.Collect(ctx)
	if err != nil {
		log.Fatal(err)
	}
	defer out.Release()
	fmt.Println(out)
}
