// Code generated by `golars transpile`. DO NOT EDIT by hand.
// Runtime applies lazy.DefaultOptimizer (predicate/slice/projection
// pushdown, CSE, simplify) on each Collect.
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
)

func main() {
	ctx := context.Background()
	df1, err := golars.ReadCSV("examples/script/data/salaries.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	lf1 := lazy.FromDataFrame(df1).
		WithColumns(expr.Col("name").Str().ToUpper().Alias("upper_name")).
		WithColumns(expr.Col("upper_name").Str().StartsWith("A").Alias("starts_a")).
		WithColumns(expr.Col("amount").Alias("yearly")).
		WithColumns(expr.Col("amount").Div(expr.LitInt64(12)).Alias("monthly")).
		WithColumns(expr.Col("amount").Gt(expr.LitInt64(100000)).Alias("big_earner")).
		WithColumns(expr.Col("upper_name").Str().Head(3).Alias("tag"))
	display(ctx, lf1.Limit(20))
}

// display collects and prints lf, releasing the result on return.
func display(ctx context.Context, lf lazy.LazyFrame) {
	out, err := lf.Collect(ctx)
	if err != nil {
		log.Fatal(err)
	}
	defer out.Release()
	fmt.Println(out)
}
