// Code generated by `golars transpile`. DO NOT EDIT by hand.
package main

import (
	"context"
	"fmt"
	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
	"log"
)

func main() {
	ctx := context.Background()
	_ = ctx
	df1, err := golars.ReadCSV("examples/script/data/salaries.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	lf2 := lazy.FromDataFrame(df1)
	lf2 = lf2.WithColumns(expr.Col("name").Str().ToUpper().Alias("upper_name"))
	lf2 = lf2.WithColumns(expr.Col("upper_name").Str().StartsWith("A").Alias("starts_a"))
	lf2 = lf2.WithColumns(expr.Col("amount").Alias("yearly"))
	lf2 = lf2.WithColumns(expr.Col("amount").Div(expr.LitInt64(12)).Alias("monthly"))
	lf2 = lf2.WithColumns(expr.Col("amount").Gt(expr.LitInt64(100000)).Alias("big_earner"))
	lf2 = lf2.WithColumns(expr.Col("upper_name").Str().Head(3).Alias("tag"))
	lf2 = lf2.Limit(20)
	{
		out, err := lf2.Collect(ctx)
		if err != nil {
			log.Fatal(err)
		}
		defer out.Release()
		fmt.Println(out)
	}
}
