// Code generated by `golars transpile`. DO NOT EDIT by hand.
package main

import (
	"context"
	"fmt"
	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
	"log"
)

func main() {
	ctx := context.Background()
	_ = ctx
	df1, err := golars.ReadCSV("examples/script/data/salaries.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	lf2 := lazy.FromDataFrame(df1)
	lf2 = lf2.Filter(expr.Col("amount").Ge(expr.LitInt64(60000)))
	// TODO(glr): command "stash" has no direct lazy API; port manually
	lf2 = lf2.Sort("amount", true)
	lf2 = lf2.Limit(2)
	// TODO(glr): command "stash" has no direct lazy API; port manually
	// error on line "use base": use: unknown frame "base" (stage it with `load ... as base` first)
	lf2 = lf2.Sort("amount", false)
	lf2 = lf2.Limit(2)
	// TODO(glr): command "stash" has no direct lazy API; port manually
	// error on line "use top_earners": use: unknown frame "top_earners" (stage it with `load ... as top_earners` first)
	// error on line "join bottom_earners on name cross": join: unknown frame "bottom_earners"
	{
		out, err := lf2.Head(10).Collect(ctx)
		if err != nil {
			log.Fatal(err)
		}
		defer out.Release()
		fmt.Println(out)
	}
}
