// Code generated by `golars transpile`. DO NOT EDIT by hand.
// Runtime applies lazy.DefaultOptimizer (predicate/slice/projection
// pushdown, CSE, simplify) on each Collect.
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
)

func main() {
	ctx := context.Background()
	df1, err := golars.ReadCSV("examples/script/data/salaries.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	lf1 := lazy.FromDataFrame(df1).
		WithColumns(expr.Col("amount").RollingMean(3, 1).Alias("ma3")).
		WithColumns(expr.Col("amount").RollingStd(3, 2).Alias("vol3")).
		WithColumns(expr.Col("amount").RollingMax(3, 1).Alias("max3")).
		WithColumns(expr.Col("amount").EWMMean(0.5).Alias("ewm"))
	display(ctx, lf1.Limit(10))
}

// display collects and prints lf, releasing the result on return.
func display(ctx context.Context, lf lazy.LazyFrame) {
	out, err := lf.Collect(ctx)
	if err != nil {
		log.Fatal(err)
	}
	defer out.Release()
	fmt.Println(out)
}
