// Code generated by `golars transpile`. DO NOT EDIT by hand.
package main

import (
	"context"
	"fmt"
	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
	"log"
)

func main() {
	ctx := context.Background()
	_ = ctx
	df1, err := golars.ReadCSV("examples/script/data/salaries.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	lf2 := lazy.FromDataFrame(df1)
	lf2 = lf2.WithColumns(expr.Col("amount").RollingMean(3, 1).Alias("ma3"))
	lf2 = lf2.WithColumns(expr.Col("amount").RollingStd(3, 2).Alias("vol3"))
	lf2 = lf2.WithColumns(expr.Col("amount").RollingMax(3, 1).Alias("max3"))
	lf2 = lf2.WithColumns(expr.Col("amount").EWMMean(0.5).Alias("ewm"))
	lf2 = lf2.Limit(10)
	{
		out, err := lf2.Collect(ctx)
		if err != nil {
			log.Fatal(err)
		}
		defer out.Release()
		fmt.Println(out)
	}
}
