// Code generated by `golars transpile`. DO NOT EDIT by hand.
package main

import (
	"context"
	"fmt"
	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
	"log"
)

func main() {
	ctx := context.Background()
	_ = ctx
	df1, err := golars.ReadCSV("examples/script/data/people.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	lf2 := lazy.FromDataFrame(df1)
	// TODO(glr): command "schema" has no direct lazy API; port manually
	{
		out, err := lf2.Head(10).Collect(ctx)
		if err != nil {
			log.Fatal(err)
		}
		defer out.Release()
		fmt.Println(out)
	}
	lf2 = lf2.Filter(expr.Col("age").Gt(expr.LitInt64(25)))
	lf2 = lf2.Sort("age", true)
	{
		out, err := lf2.Head(10).Collect(ctx)
		if err != nil {
			log.Fatal(err)
		}
		defer out.Release()
		fmt.Println(out)
	}
}
