// Code generated by `golars transpile`. DO NOT EDIT by hand.
// REPL-only commands skipped: frames.
// Runtime applies lazy.DefaultOptimizer (predicate/slice/projection
// pushdown, CSE, simplify) on each Collect.
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/dataframe"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
)

func main() {
	ctx := context.Background()
	df1, err := golars.ReadCSV("examples/script/data/people.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	people := lazy.FromDataFrame(df1)
	df2, err := golars.ReadCSV("examples/script/data/salaries.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df2.Release()
	salaries := lazy.FromDataFrame(df2)
	lf2 := salaries.
		Filter(expr.Col("amount").Ge(expr.LitInt64(50000))).
		Join(people, []string{"name"}, dataframe.InnerJoin).
		Sort("amount", true).
		Limit(5)
	display(ctx, lf2.Limit(10))
}

// display collects and prints lf, releasing the result on return.
func display(ctx context.Context, lf lazy.LazyFrame) {
	out, err := lf.Collect(ctx)
	if err != nil {
		log.Fatal(err)
	}
	defer out.Release()
	fmt.Println(out)
}
