// Code generated by `golars transpile`. DO NOT EDIT by hand.
package main

import (
	"context"
	"fmt"
	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/dataframe"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
	"log"
)

func main() {
	ctx := context.Background()
	_ = ctx
	df1, err := golars.ReadCSV("examples/script/data/people.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	lf2 := lazy.FromDataFrame(df1)
	// staged frame "people" as lf2
	df3, err := golars.ReadCSV("examples/script/data/salaries.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df3.Release()
	lf4 := lazy.FromDataFrame(df3)
	// staged frame "salaries" as lf4
	lf2 = lf2.Filter(expr.Col("age").Gt(expr.LitInt64(25)))
	lf4 = lf4.Filter(expr.Col("amount").Ge(expr.LitInt64(50000)))
	lf4 = lf4.Join(lf2, []string{"name"}, dataframe.InnerJoin)
	lf4 = lf4.Sort("amount", true)
	lf4 = lf4.Limit(5)
	{
		out, err := lf4.Head(10).Collect(ctx)
		if err != nil {
			log.Fatal(err)
		}
		defer out.Release()
		fmt.Println(out)
	}
}
