// Code generated by `golars transpile`. DO NOT EDIT by hand.
package main

import (
	"context"
	"fmt"
	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
	"log"
)

func main() {
	ctx := context.Background()
	_ = ctx
	df1, err := golars.ReadCSV("examples/script/data/orders.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	lf2 := lazy.FromDataFrame(df1)
	lf2 = lf2.WithColumns(expr.Col("discount").FillNullExpr(expr.LitFloat64(0)).Alias("discount_filled"))
	lf2 = lf2.WithColumns(expr.Col("unit_price").Mul(expr.LitInt64(1).Sub(expr.Col("discount_filled"))).Alias("revenue"))
	{
		out, err := lf2.Head(10).Collect(ctx)
		if err != nil {
			log.Fatal(err)
		}
		defer out.Release()
		fmt.Println(out)
	}
	// TODO(glr): command "reset" has no direct lazy API; port manually
	df3, err := golars.ReadCSV("examples/script/data/orders.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df3.Release()
	lf4 := lazy.FromDataFrame(df3)
	lf4 = lf4.Filter(expr.Col("discount").IsNotNull())
	{
		out, err := lf4.Head(10).Collect(ctx)
		if err != nil {
			log.Fatal(err)
		}
		defer out.Release()
		fmt.Println(out)
	}
}
