// Code generated by `golars transpile`. DO NOT EDIT by hand.
// Runtime applies lazy.DefaultOptimizer (predicate/slice/projection
// pushdown, CSE, simplify) on each Collect.
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/Gaurav-Gosain/golars"
	"github.com/Gaurav-Gosain/golars/dataframe"
	"github.com/Gaurav-Gosain/golars/expr"
	"github.com/Gaurav-Gosain/golars/io/csv"
	"github.com/Gaurav-Gosain/golars/lazy"
)

func main() {
	ctx := context.Background()
	df1, err := golars.ReadCSV("examples/script/data/salaries.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df1.Release()
	salaries := lazy.FromDataFrame(df1)
	df2, err := golars.ReadCSV("examples/script/data/people.csv", csv.WithNullValues(""))
	if err != nil {
		log.Fatal(err)
	}
	defer df2.Release()
	lf2 := lazy.FromDataFrame(df2).
		Join(salaries, []string{"name"}, dataframe.InnerJoin).
		Sort("age", true).
		Filter(expr.Col("age").Gt(expr.LitInt64(20)))
	// Implicit display: no show/head/collect/save in script.
	display(ctx, lf2)
}

// display collects and prints lf, releasing the result on return.
func display(ctx context.Context, lf lazy.LazyFrame) {
	out, err := lf.Collect(ctx)
	if err != nil {
		log.Fatal(err)
	}
	defer out.Release()
	fmt.Println(out)
}
